#!/bin/sh

MINCAML_HOME=$(cd "$(dirname "$0")"/../../ && pwd)
CP_DIR="$MINCAML_HOME/netbeans/lib"
CP="$MINCAML_HOME/netbeans/lib/java-cup-11b-runtime.jar:$MINCAML_HOME/netbeans/src/"
exec java -enableassertions -cp "$CP" Main "$@"
